--
engines:
  duplication:
    enabled:false
    config:
      languages:
        - javascript
  rubocop:
    enabled: true
  jslint:
    enabled: true
  stylelint:
    enabled: true
  fixme:
    enabled: true
  haml-lint:
    enabled: true
  ratings:
    paths:
      - "**.css"
      - "**.js"
      - "**.html"
      - "**.rb"
      - "**.haml"
  exclude_paths:
    - static/javascript/jquery.*.js
