--
engines:
  rubocop:
    enabled: true
  jslint:
    enabled: true
  stylelint:
    enabled: true
  fixme:
    enabled: true
  haml-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - html
        -javascript
  ratings:
    paths:
      - "**.css"
      - "**.js"
      - "**.html"
      - "**.rb"
      - "**.haml"
  exclude_paths:
    - static/javascript/jquery.*.js
