version: 2
plugins:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  stylelint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - html
exclude_patterns:
  - static/javascript/jquery.*.js
