source "https://rubygems.org"


gem "bcrypt-ruby",    "= 3.1.5"
gem "log4r",     "= 1.1.10"
gem "ipaddress", "= 0.8.0"
gem "ruby_protobuf",  "= 0.4.11"
gem "json",      "= 1.8.1"
gem "datamapper"
gem "dm-aggregates"
gem "dm-do-adapter"
gem "dm-migrations"
gem "dm-postgres-adapter"
gem "dm-sqlite-adapter"
gem "dm-transactions"
gem "dm-types"
gem "dm-validations"
gem "sanitize", "= 2.1.0"
gem "rmail", "= 1.1.0"
gem "thin", "= 1.6.3"
gem "haml", "= 4.0.5"
gem "RedCloth", "= 4.2.9"
gem "rack", "= 1.5.2"
gem "rack-protection", "= 1.5.2"
gem "rack-flash3", "= 1.0.5"
gem "tilt", "= 1.4.1"
gem "sinatra", "~> 1.4.5"
gem "locale", "= 2.1.0"

group :test do
  gem "simplecov", :require => false
  gem "rack-test", "= 0.6.3"
  gem "webmock",   "= 1.19.0"
  gem "timecop",   "= 0.7.1"
end
